apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  AZURE_STORAGE_ACCOUNT_NAME: {{ default "" .Values.secret.AZURE_STORAGE_ACCOUNT_NAME | b64enc | quote }}
  AZURE_STORAGE_PRIMARY_ACCOUNT_KEY: {{ default "" .Values.secret.AZURE_STORAGE_PRIMARY_ACCOUNT_KEY | b64enc | quote }}

